export const ADD_INGREDIENT ='ADD_INGREDIENT'
export const REM_INGREDIENT ='REM_INGREDIENT'
export const SET_INGREDIENT ='SET_INGREDIENT'
export const FAILED_INGREDIENT ='FAILED_INGREDIENT'

export const ORDER_SUCCESS ='ORDER_SUCCESS'
export const ORDER_FAILED ='ORDER_FAILED'
export const ORDER_BURGER_STARTED ='ORDER_BURGER_STARTED'

export const FETCH_ORDER_SUCCESS ='FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAILED ='FETCH_ORDER_FAILED'
export const FETCH_ORDER_STARTED ='FETCH_ORDER_STARTED'

export const AUTH_STARTED ='AUTH_STARTED'
export const AUTH_SUCCESS ='AUTH_SUCCESS'
export const AUTH_FAILED ='AUTH_FAILED'
export const LOGOUT_USER ='LOGOUT_USER'
export const REDIRECT_FROM_AUTH ='REDIRECT_FROM_AUTH'



